apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: course-backend
spec:
  ingressClassName: nginx
  rules:
    - host: course.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: course-backend
                port:
                  number: 8080
